version: '3.3'
services:
    api:
      build: ./out_api/ex_react_2_api
      image: erwankerbrat/exemple_react_3_api
      ports:
        - "1020:5000" 
      environment:
        DATABASE_URL: "mysql://root:rootpassword@db:3306/db_test"
    db:
      image: erwankerbrat/copie_mysql
      volumes:
       - ./data-init:/docker-entrypoint-initdb.d  
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_test
          MYSQL_USER: username
          MYSQL_PASSWORD: password
#    front_resto:
#      build: ./out_react/front
#      image: erwankerbrat/exemple_react_3_front
#      ports:
#        - "1021:3000" 
#      environment:
#        REACT_APP_API_ULR: "http://127.0.0.1:1021"
